### ISSUE TITLE
Does UI required for the backend exercise?

### ISSUE THREAD

**Issue by zeshan77** [Accredifysg/Dev-Interview#10]
Hi,

Do we need to create UI for the backend exercises or we may consume the endpoints by using a client i.e Postman etc?

Thanks

**Comment by JasonNeo** [comment]
Hi @zeshan77, a simple UI will do. 
An ideal solution is one that demonstrates sound software design and attention to user experience.

**Comment by ChenRen93** [comment]
resolve #10
