### ISSUE TITLE
Request body looks different

### ISSUE THREAD

**Issue by Matchstick92** [Accredifysg/Dev-Interview#14]
Exercise 1 uses `patient_nationality` and exercise 3 uses `patientNationality`. Is this intentional?

**Comment by edwinkkh** [comment]
Hi @Matchstick92,

The [question](https://accredify.notion.site/Backend-Questions-03f60aeb923d4a71ba6e91ec4c2c8cde) has been updated.  Patient nationality is supposed to be camel case. 
There is a typo on the question, thanks for spotting it.
