### ISSUE TITLE
Sort all the hashes from the previous step alphabetically and hash them all together using sha256. This will provide the target hash of the file.

### ISSUE THREAD

**Issue by Neeraj824** [Accredifysg/Dev-Interview#16]
Can you please explain in this step. I am trying to convert this 
[
  "8d79f393cc294fd3daca0402209997db5ff8a2ad1a498702f0956952677881ae",
  "cd77eab0fa4b92136f883dfe6fe63d7ee68a98a7697874609a5f9d24adaa0f04",
  "d94a0e7c2e7f61c7b29fede334c1b501a8b7cc8d46876273e92c4412ad82f575",
  "b38da593123c5295845996b08502a115c2ed5e1f42745ed45fba2a0b4ea3ed47",
  "88e287c3b0e2fcaeac173b7a20e3357342ad75cb2ceb849b3f7176c4026379b2",
  "9cba7ec835e861763731506e3b7712cfcab46ccb735fadd9a4e7c85716972144",
  "39fa9881a7607ee77cfaa82b982f4e809fc96c8ebf4891d98349ba3d71bc1a8e",
  "14ee1b33dd3084a127a6e2e6807fca79f317e2df3a9069c50e5f5adb4da84bb8",
  "a8aa49c6d150fab1fd77213f1f182c42ece261b30822b0c1c12826ef4599238b",
]
and convert to sha256 it is returning "034cd64b68183c9eb3be3e96062404ec7b4788bb06b294cc74d452eb4a96b014" 

and if we sort this array alphabetically 

[
  "8d79f393cc294fd3daca0402209997db5ff8a2ad1a498702f0956952677881ae",
  "9cba7ec835e861763731506e3b7712cfcab46ccb735fadd9a4e7c85716972144",
  "14ee1b33dd3084a127a6e2e6807fca79f317e2df3a9069c50e5f5adb4da84bb8",
  "39fa9881a7607ee77cfaa82b982f4e809fc96c8ebf4891d98349ba3d71bc1a8e",
  "88e287c3b0e2fcaeac173b7a20e3357342ad75cb2ceb849b3f7176c4026379b2",
  "a8aa49c6d150fab1fd77213f1f182c42ece261b30822b0c1c12826ef4599238b",
  "b38da593123c5295845996b08502a115c2ed5e1f42745ed45fba2a0b4ea3ed47",
  "cd77eab0fa4b92136f883dfe6fe63d7ee68a98a7697874609a5f9d24adaa0f04",
  "d94a0e7c2e7f61c7b29fede334c1b501a8b7cc8d46876273e92c4412ad82f575",
]

and convert to sha256 it is returning "2c2d334ef223014ec0480c432dd46fd0e6c33cc0be7257b6dd8733bf28d63463" 

I need your assistance here what you want to say in this step.

**Comment by edwinkkh** [comment]
Hi @Neeraj824,

Your hashes are not in the proper order. To obtain the right SHA 256 results, you must eliminate all white spaces and the new break line before hashing.

**Comment by Neeraj824** [comment]
Hi @edwinkkh,

can you please explain hashes are not in the proper order what is mean? 


if I am doing with ["8d79f393cc294fd3daca0402209997db5ff8a2ad1a498702f0956952677881a","9cba7ec835e861763731506e3b7712cfcab46ccb735fadd9a4e7c85716972144","14ee1b33dd3084a127a6e2e6807fca79f317e2df3a9069c50e5f5adb4da84bb8","39fa9881a7607ee77cfaa82b982f4e809fc96c8ebf4891d98349ba3d71bc1a8e","88e287c3b0e2fcaeac173b7a20e3357342ad75cb2ceb849b3f7176c4026379b2","a8aa49c6d150fab1fd77213f1f182c42ece261b30822b0c1c12826ef4599238b","b38da593123c5295845996b08502a115c2ed5e1f42745ed45fba2a0b4ea3ed47","cd77eab0fa4b92136f883dfe6fe63d7ee68a98a7697874609a5f9d24adaa0f04","d94a0e7c2e7f61c7b29fede334c1b501a8b7cc8d46876273e92c4412ad82f575"] then getting "**c1638644034a05303dde0744006e0c9a616e2eb7059f335958b40c6ebee7ae0d**" 

or if I am doing with this ["8d79f393cc294fd3daca0402209997db5ff8a2ad1a498702f0956952677881ae","cd77eab0fa4b92136f883dfe6fe63d7ee68a98a7697874609a5f9d24adaa0f04","d94a0e7c2e7f61c7b29fede334c1b501a8b7cc8d46876273e92c4412ad82f575","b38da593123c5295845996b08502a115c2ed5e1f42745ed45fba2a0b4ea3ed47","88e287c3b0e2fcaeac173b7a20e3357342ad75cb2ceb849b3f7176c4026379b2","9cba7ec835e861763731506e3b7712cfcab46ccb735fadd9a4e7c85716972144","39fa9881a7607ee77cfaa82b982f4e809fc96c8ebf4891d98349ba3d71bc1a8e","14ee1b33dd3084a127a6e2e6807fca79f317e2df3a9069c50e5f5adb4da84bb8","a8aa49c6d150fab1fd77213f1f182c42ece261b30822b0c1c12826ef4599238b"]

then getting "**96a33b562dbd2242fa35656fe84493e449b760777200a6e220b43623008a272d**".

**Comment by edwinkkh** [comment]
Hi @Neeraj824 

The hashes are not sorted in alphabetically order. There are [online tools](https://alphabetizer.flap.tv/) that assist you to validate if the hash order are correct.

**Comment by Neeraj824** [comment]
I have attached the image below but still the i am not able to get the correct result.

Can you please share the example same link Step 2 you defined. 

<img width="780" alt="Screenshot 2023-02-22 at 5 50 46 PM" src="https://user-images.githubusercontent.com/53514637/220585089-aebbe853-c010-4340-b036-dfa6061c5194.png">
<img width="1280" alt="Screenshot 2023-02-22 at 5 52 12 PM" src="https://user-images.githubusercontent.com/53514637/220585112-9ba26ca0-4a37-4380-b7ef-7632d448f7e8.png">

**Comment by edwinkkh** [comment]
Hi @Neeraj824,

You have to [remove all whitespaces](https://www.browserling.com/tools/remove-all-whitespace) as mentioned over [here](https://github.com/Accredifysg/Dev-Interview/issues/16#issuecomment-1439575003) before hashing the value.

**Comment by Neeraj824** [comment]
@edwinkkh, Thanks finally  i have achieved the Step 3.
<img width="780" alt="Screenshot 2023-02-22 at 5 50 46 PM" src="https://user-images.githubusercontent.com/53514637/220810431-13ef579f-b2d1-47f2-86b3-853477b64e6c.png">


In Condition 2, I have to read this URL "**https://dns.google/resolve?name=ropstore.accredify.io&type=TXT**" and compare the value of "ropstore.accredify.io." in JSON.

Can you please let me know this is correct step you want in code?

**Comment by edwinkkh** [comment]
Hi @Neeraj824,

In condition 2. we are comparing the values of `data.issuer.identityProof.key` with `https://dns.google/resolve?name=<url>&type=TXT`. The key need to match with one of the values under `Answers` section from google.

The **url** is retrieved under  `data.issuer.identityProof.location`

**Comment by Neeraj824** [comment]
@edwinkkh, Got it. Thanks
