### ISSUE TITLE
Issue facing in Condition 3 during the implementation

### ISSUE THREAD

**Issue by neerajpoptv** [Accredifysg/Dev-Interview#17]
**1st Approach**

After Reading the "**63ca218f30663774f60048cc-1.oa**" file. I have created below json.

{"id":"060b683c-f884-41cb-9988-23726c77d09a:string:63ca218f30663774f60048cc-1"}
{"name":"c9136dde-d086-4281-8702-a6745801dca4:string:Pathway Full Certificate 1"}
{"recipient.name":"dba39b18-ce80-4915-b3cd-8221dfbd3e8d:string:Hamachan"}
{"recipient.email":"3cacee7e-9c7a-4dfc-8d1c-ab6a3193545c:string:hamasaki@accredify.io"}
{"issuer.name":"4e14ee1c-1e88-4316-98ea-925f72aa63b9:string:School of Dog Trainers"}
{"issuer.identityProof.type":"e5b1dd47-249b-4ffd-a563-6d1631b00466:string:DNS-DID"}
{"issuer.identityProof.key":"xf44a44e0-0021-4179-8868-aa7145579797:string:did:ethr:0xad4dbc3ad9dc3b7f52609d5b23f3c22e3e7cefa1#controller"}
{"issuer.identityProof.location":"0dbe46d0-879c-4c0a-8288-95b2d0f0e436:string:ropstore.accredify.io"}
{"issued":"acda0148-c381-4428-8e93-b77207bf6928:string:2023-01-20T00:00:00+08:00"}

**Question:**: Is this json is correct for encryption.If yes then i have followed the below string
[
    "90db704ac035590087bc9b85e74d12b49071e6d393e9dafd9c703c13aee90d93",
    "37a59a13e5bf812efdb93bf1cc9a95b581f50cf977f3d80edef219deb0ec4d45"
    "fbc5cae86080c842bcfe8f5e8d6fa10c850d157e28488576d86d4c8df32ae598"
    "4ef90e8c36ca1fc276e733edaea1d006bb577db2fb82fa1312b55f989ec0c9e8"
    "d7864d926b56b44a5fafce175ec35aaa07e6d922fe6db8dcb7ed679d1c35c88e"
    "be19dfc83d63500fe1b75d750905e9826a9718033b1729d9490dbeb8d966049e"
    "dc5ea8c2cfc9ff2c372ec0822e01cef5352edd3bbda080dae2b8d4501e143975",
    "72aaaac8379876e40d918633ee7af5ce07a9a0e61912ab22d8d2c7e8ee7ebc3d"
    "efbac12523cf8a3fb573807285a9299d2fabb778b68185b888cbce9f0e3137ed"
]

**Alphabetically order**
[
    "37a59a13e5bf812efdb93bf1cc9a95b581f50cf977f3d80edef219deb0ec4d45",
    "4ef90e8c36ca1fc276e733edaea1d006bb577db2fb82fa1312b55f989ec0c9e8",
    "72aaaac8379876e40d918633ee7af5ce07a9a0e61912ab22d8d2c7e8ee7ebc3d",
    "90db704ac035590087bc9b85e74d12b49071e6d393e9dafd9c703c13aee90d93",
    "be19dfc83d63500fe1b75d750905e9826a9718033b1729d9490dbeb8d966049e",
    "d7864d926b56b44a5fafce175ec35aaa07e6d922fe6db8dcb7ed679d1c35c88e",
    "dc5ea8c2cfc9ff2c372ec0822e01cef5352edd3bbda080dae2b8d4501e143975",
    "efbac12523cf8a3fb573807285a9299d2fabb778b68185b888cbce9f0e3137ed",
    "fbc5cae86080c842bcfe8f5e8d6fa10c850d157e28488576d86d4c8df32ae598",
]

**Removed Spacing:**
["37a59a13e5bf812efdb93bf1cc9a95b581f50cf977f3d80edef219deb0ec4d45","4ef90e8c36ca1fc276e733edaea1d006bb577db2fb82fa1312b55f989ec0c9e8","72aaaac8379876e40d918633ee7af5ce07a9a0e61912ab22d8d2c7e8ee7ebc3d","90db704ac035590087bc9b85e74d12b49071e6d393e9dafd9c703c13aee90d93","be19dfc83d63500fe1b75d750905e9826a9718033b1729d9490dbeb8d966049e","d7864d926b56b44a5fafce175ec35aaa07e6d922fe6db8dcb7ed679d1c35c88e","dc5ea8c2cfc9ff2c372ec0822e01cef5352edd3bbda080dae2b8d4501e143975","efbac12523cf8a3fb573807285a9299d2fabb778b68185b888cbce9f0e3137ed","fbc5cae86080c842bcfe8f5e8d6fa10c850d157e28488576d86d4c8df32ae598"]

**Sha256**
496fa276f92883e7ba92101456784ca1f8138a6a81964366c6552d0ad78caca3 is wrong.

**2nd Approach**

After Reading the "**63ca218f30663774f60048cc-1.oa**" file and consider the json defined in example I have created below json.

{"id":"63ca218f30663774f60048cc-1"}
{"name":"Pathway Full Certificate 1"}
{"recipient.name":"Hamachan"}
{"recipient.email":"hamasaki@accredify.io"}
{"issuer.name":"School of Dog Trainers"}
{"issuer.identityProof.type":"DNS-DID"}
{"issuer.identityProof.key":"did:ethr:0xad4dbc3ad9dc3b7f52609d5b23f3c22e3e7cefa1#controller"}
{"issuer.identityProof.location":"ropstore.accredify.io"}
{"issued":"2023-01-20T00:00:00+08:00"}

**Question:**: Is this json is correct for encryption.If yes then i have followed the below string
[
  "dfe740c182f3a8b1ef8b81bd562cf2cb7f077476da70bbef5264b265baa55ef6",
  "26a5fc125990ffd236e6b5a1d8ad9d48fb787ac4c3fea6a8dd0212f5a45cbf56",
  "3e46d1a6e7d159bfc74bc42fda6f22d090363e70b14c2bfa23e268c31e3647c1",
  "1db5f808ab2548433bee2c58ff7bbc4b415d765df6a4c52d4ea7823d31df7668",
  "ed7f8fdcf0142afd4b50bfe7a5933ad9d67e40435124163e1f954081db2dd9c1",
  "9cba7ec835e861763731506e3b7712cfcab46ccb735fadd9a4e7c85716972144",
  "e62e6c33b2f3564a660116931d6e8750294ff64e40a368f310bd0bd04daef443",
  "14ee1b33dd3084a127a6e2e6807fca79f317e2df3a9069c50e5f5adb4da84bb8",
  "ab8c5095376abde4c8720e73faf7ab7627a471d7048cc9d20457cc50f6144412",
]

**Alphabetically order**
[
"14ee1b33dd3084a127a6e2e6807fca79f317e2df3a9069c50e5f5adb4da84bb8",
"1db5f808ab2548433bee2c58ff7bbc4b415d765df6a4c52d4ea7823d31df7668",
"26a5fc125990ffd236e6b5a1d8ad9d48fb787ac4c3fea6a8dd0212f5a45cbf56",
"3e46d1a6e7d159bfc74bc42fda6f22d090363e70b14c2bfa23e268c31e3647c1",
"9cba7ec835e861763731506e3b7712cfcab46ccb735fadd9a4e7c85716972144",
"ab8c5095376abde4c8720e73faf7ab7627a471d7048cc9d20457cc50f6144412",
"dfe740c182f3a8b1ef8b81bd562cf2cb7f077476da70bbef5264b265baa55ef6",
"e62e6c33b2f3564a660116931d6e8750294ff64e40a368f310bd0bd04daef443",
"ed7f8fdcf0142afd4b50bfe7a5933ad9d67e40435124163e1f954081db2dd9c1"
]

**Removed Spacing:**
["14ee1b33dd3084a127a6e2e6807fca79f317e2df3a9069c50e5f5adb4da84bb8","1db5f808ab2548433bee2c58ff7bbc4b415d765df6a4c52d4ea7823d31df7668","26a5fc125990ffd236e6b5a1d8ad9d48fb787ac4c3fea6a8dd0212f5a45cbf56","3e46d1a6e7d159bfc74bc42fda6f22d090363e70b14c2bfa23e268c31e3647c1","9cba7ec835e861763731506e3b7712cfcab46ccb735fadd9a4e7c85716972144","ab8c5095376abde4c8720e73faf7ab7627a471d7048cc9d20457cc50f6144412","dfe740c182f3a8b1ef8b81bd562cf2cb7f077476da70bbef5264b265baa55ef6","e62e6c33b2f3564a660116931d6e8750294ff64e40a368f310bd0bd04daef443","ed7f8fdcf0142afd4b50bfe7a5933ad9d67e40435124163e1f954081db2dd9c1"]

**Sha256**
b5b76dffc8ae1a3aebf881eb73c126590700631555994ed85b45209d5d2f48d1 is wrong.

Can you please let know where i am doing wrong to validate it.

**Comment by edwinkkh** [comment]
Hi @neerajpoptv,

Please check the json structure for both of your approaches.  For approach one, you are supposed to use the simplified version of [json](https://www.notion.so/accredify/Technical-Assessment-for-Senior-Laravel-Developer-de808af21ca249ba8f4b2d8f1aaf2a66?pvs=4#b99d150acead43028d7ea636654a4a42). The "**63ca218f30663774f60048cc-1.oa"** file would not work as it has additional steps to calculate SHA-256. 

The SHA-256 value is correct for the second approach. You might want to check your json structure.

**Comment by Abdulhakimsg** [comment]
Closing this issue as candidate has handed in assignment
