### ISSUE TITLE
Submission for Junior Frontend Developer by Tim Wong

### ISSUE THREAD

**Issue by T31K** [Accredifysg/Dev-Interview#8]
Hi Hakim,

Here's the [link](https://github.com/T31K/accredify-test) to the repo for the test:

**Comment by T31K** [comment]
I've updated the app to consume an external free API.
I've also added Unit/e2e tests. They may be incorrect, but I've attempted to complete them to the best of my ability after reading up/watching a myriad of youtube tutorials.

**Comment by Abdulhakimsg** [comment]
Great! 

will get the team to take a look
